project:
  type: book
  output-dir: _book

book:
  title: "AutoGen Tutorial"
  author: "Chris Snow"
  chapters:
    - index.qmd
    - part: "Autogen Introduction"
      chapters:
        - work/01_intro/01_Python_Asyncio.ipynb
        - work/01_intro/02_OpenAI_Client.ipynb
    - part: "Agent Introduction"
      chapters:
        - work/02_agents/01_First_Agent.ipynb
        - work/02_agents/02_Multi_Modal.ipynb
        - work/02_agents/03_Structured_Output.ipynb
        - work/02_agents/04_Tools_Intro.ipynb
        - work/02_agents/05_MCP_Intro.ipynb
        - work/02_agents/06_Workbench.ipynb
        - work/02_agents/07_Built_in_Tools.ipynb
        - work/02_agents/08_Advanced_Tool_Usage.ipynb
        - work/02_agents/09_Agent_as_Tool.ipynb
        - work/02_agents/10_Managing_Model_Context.ipynb
        - work/02_agents/11_Exploring_Preset_Agents.ipynb
        - work/02_agents/12_AssistantAgent_Conclustion.ipynb
    - part: UserProxyAgent
      chapters: 
        - work/03_userproxyagent/01_Intro.ipynb
        - work/03_userproxyagent/02_Sample.ipynb
format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
  epub:
    toc: true
