project:
  type: book
  output-dir: _book

book:
  title: "AutoGen Tutorial"
  author: "Chris Snow"
  chapters:
    - index.qmd
    - work/00_Python_Asyncio.ipynb
    - work/01_OpenAI_Client.ipynb
    - work/02_First_Agent.ipynb
    - work/03_Multi_Modal.ipynb
    - work/04_Structured_Output.ipynb
    - work/05_Tools_Intro.ipynb
    - work/06_MCP_Intro.ipynb
    - work/07_Workbench.ipynb
    - work/08_Built_in_Tools.ipynb
    - work/09_Agent_as_Tool.ipynb
    - work/10_Advanced_Tool_Usage.ipynb
    - work/11_Managing_Model_Context.ipynb
    - work/12_Exploring_Preset_Agents.ipynb
    - work/13_AssistantAgent_Conclustion.ipynb

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
  epub:
    toc: true
